In [2]:
import numpy as np
import scipy
a = np.array([0, 0, 10, 0, 0], dtype=float)
w = np.array([1/3, 1/3, 1/3])
scipy.ndimage.convolve1d(a, w)

array([0.        , 3.33333333, 3.33333333, 3.33333333, 0.        ])

In [3]:
a = np.array([0, 0, 10, 0, 0], dtype=float)
w = np.array([1/4, 1/2, 1/4])
scipy.ndimage.convolve1d(a, w)

array([0. , 2.5, 5. , 2.5, 0. ])

In [4]:
a = np.array([0, 0, 0, 10, 0, 0, 0], dtype=float)
w = np.array([1/12, 1/6, 1/2, 1/6, 1/12])
scipy.ndimage.convolve1d(a, w)

array([0.        , 0.83333333, 1.66666667, 5.        , 1.66666667,
       0.83333333, 0.        ])

In [5]:
a = np.zeros((5, 5))
a[2, 2] = 10
a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [6]:
w = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]], dtype=float)
w /= w.sum()
scipy.ndimage.convolve(a, w)

array([[0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.625, 1.25 , 0.625, 0.   ],
       [0.   , 1.25 , 2.5  , 1.25 , 0.   ],
       [0.   , 0.625, 1.25 , 0.625, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ]])

In [34]:
img_arr = np.array([[13, 20, 17, 58], [87, 23, 45, 27], [77, 19, 28, 55]], dtype=float)
weights_array = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]], dtype=float)
k = (np.shape(weights_array)[0]-1)//2
sh = np.shape(img_arr)
print(sh)
def pad(img_array, weights_array, k, sh):
    k1 = sh[0]
    k2 = sh[1]
    n1 = k1 + 2*k
    n2 = k2 + 2*k
    fin_arr = np.array([[0] * n2] * n1, dtype=float)
    for i in range(k1):
        for j in range(k2):
            fin_arr[i + k][j + k] = img_array[i][j]
    return fin_arr
fin_arr = pad(img_arr, weights_array, k, sh)
print(fin_arr)
def blur(img_array, weights_array, n, sh):
    k1 = sh[0]
    k2 = sh[1]
    for i in range(k1 + k + 1):
        for j in range(k2 + k + 1):
            for x in range(n):
                for y in range(n):
                    img_array[i + x][j + y] += weights_array[x][y]
    return img_array
print(blur(fin_arr, weights_array, k, sh))

(3, 4)
[[ 0.  0.  0.  0.  0.  0.]
 [ 0. 13. 20. 17. 58.  0.]
 [ 0. 87. 23. 45. 27.  0.]
 [ 0. 77. 19. 28. 55.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.  0.]
 [ 1. 14. 21. 18. 59.  0.]
 [ 1. 88. 24. 46. 28.  0.]
 [ 1. 78. 20. 29. 56.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
